### ISSUE TITLE
ReferenceError: sessionStorage is not defined

### ISSUE THREAD

**Issue by centricadean** [vlocityinc/vlocity_build#493] opened 2022-07-27 13:22 UTC
**Summary**

When using local compile, a `sessionStorage is not defined error` appears when trying to compile Industries CPQ LWC cart FlexCards. 

The error appears to be related to this file: `/vlocity-temp/plugins/@vlocity-cme/flexcard-compiler/src/compiler/flexCardUtility/fetchCustomLabels.js`

Commenting out the sessionStorage lines allows the FlexCards to compile but then they error in Salesforce:

![Screenshot 2022-07-27 at 2 23 59 pm](https://user-images.githubusercontent.com/104971277/181257899-7839f680-0a29-4fd4-97f0-1496e6d00f3b.png)

**Steps to reproduce:**

1. Set the job file to use the vlocity-cme compiler (make sure you include your npm auth key):

```
lwcCompilerVersion: "900"
lwcCompilerNamespace: "vlocity-cme"
```

2. Make sure you have the VlocityCard folder with the LWC cart FlexCards (follow instructions here to download from Static Resources https://docs.vlocity.com/en/Deploy-Industries-CPQ-in-LWC-with-OmniStudio-Disabled.html) 

3. Run packDeploy

4. If you get an error with copy-anything, use @2.0.1 or @2.0.6 - if you use @2.0.6, see here https://github.com/vlocityinc/vlocity_build/issues/475#issuecomment-1196604605

5. Run packDeploy again, it will compile some FlexCards and then it will give you an error saying ReferenceError: sessionStorage is not defined

![Screenshot 2022-07-27 at 1 40 02 pm](https://user-images.githubusercontent.com/104971277/181257311-9290f679-18df-475d-91b8-1eb17ab6912f.png)

Running vlocity 1.15.6 in the vlocity_cmt namespace

**Comment by KevinGossentCap** [comment] 2022-08-08 16:26
Hi,
I've got the exact same problem and error without specifying lwcCompilerNamespace but setting lwcCompilerVersion to 236.2 (which is the actual vlocity version while package is 900.456.3 corresponding to CME 236.2.3.900.456.3 ...)

**Comment by KevinGossentCap** [comment] 2022-08-09 07:10
Even easier way to reproduce

1. Ask for an ESM trail org : https://success.vlocity.com/s/application-suite-detail?Id=a443m0000006rxkAAA&library=aBQo0000000PAsRGAW (I used 236.2.4)
2. sfdx connect to it
3. download, unzip and regroup components from CPQ static resources: CPQ_browse_flexcards, CPQ_cart_flexcards, CPQ_common_flexcards, CPQ_config_flexcards, CPQ_multisite_flexcards, CPQ_DR_IP_OS, and CPQ_assets_flexcards
4. build your YAML file with parameters to point to the right directory & npmAuthKey & lwcCompilerVersion
5. Manifest in YAML can be limited to OmniScript/CPQ_cartConfigurator_Multi-Language & VlocityCard/cpqProductTileList
6. run the command (in my case "vlocity -propertyfile .\vlocity\properties\vlocity.properties -job .\vlocity\YAML\CPQ_LWC_3.yaml packDeploy" ; I use propertyfile to give sf.username)
7. See the crash (if you get the copy-anything error, prefer replace the retrieved one with version 2.0.1 and relaunch same command)

**Comment by KevinGossentCap** [comment] 2022-08-19 13:27
@centricadean I've been told trough a Salesforce Case that this error is to be corrected with version 240 (winter 23).
We'll see how it will arrive, and if we can use it or not with previous versions of the managed package (like using the 240 compiler for the 236 managed package...)

**Comment by centricadean** [comment] 2022-08-19 14:22
> 

Yeah I got the same message, will be keeping an eye on this too

**Comment by centricadean** [comment] 2022-08-19 14:22
> @centricadean I've been told trough a Salesforce Case that this error is to be corrected with version 240 (winter 23).
> We'll see how it will arrive, and if we can use it or not with previous versions of the managed package (like using the 240 compiler for the 236 managed package...)

Yeah I got the same message, will keep an eye on it

**Comment by manas-sf** [comment] 2022-11-09 16:42
Is it still an issue with VBT # 1.16.0?

**Comment by centricadean** [comment] 2022-11-09 16:43
@manas-sf yes

**Comment by KevinGossentCap** [comment] 2022-11-09 16:59
I confirm also, still present with ESM components (at least)

**Comment by manas-sf** [comment] 2022-11-09 18:35
Ok. I think it's an issue with the compiler so FlexCards need to be activated with Puppeteer only for now. Can you please provide Support Case Id or raise new a case and ask them to assign to FlexCard team providing all the details. Thanks.

**Comment by agarcia-sf** [comment] 2022-11-10 01:35
I am reopening this issue to keep track.

@centricadean I see that this issue is still happening. Have you tried the latest 240 package? If the error is still happening on that package we should take a look and fix on the compiler side.

**Comment by centricadean** [comment] 2022-11-10 08:52
@agarcia-sf thank you - yes the issue is still alive and kicking in the latest version of VBT and with v240. I raised another issue outlining what I found to be broken in the @vlocity-cme plugin which is in the Vlocity repo. Please see issue https://github.com/vlocityinc/vlocity_build/issues/520

So there are two outstanding issues:

- @vlocity-cme plugin
- /v1/GenericInvoke API method is still broken in v240 (which was supposed to be fixed as per GUS)

**Comment by PradeepSF** [comment] 2022-11-14 10:31
@agarcia-sf we have removed the use of SessionStorage on flexcard PR:  https://github.com/sf-industries/via_cards/pull/465/files from 240 a while base when @centricadean  mentioned CASE 43467130, Any idea why @vlocity-cme still has old codes.

**Comment by KevinGossentCap** [comment] 2022-11-28 17:09
Just tried with latest VBT and latest SFI version (CMT 240.8)
Took only 1 omniscript & 1 vlocitycard
OmniScript/CPQ_cartConfigurator_Multi-Language
VlocityCard/cpqProductTileList

OS compiles OK
Card gives a strange error
  Compiling Flexcard with  FlexCard ID:  >> a5a6S000007JdoAQAS
APEX_ERROR: System.LimitException: JSON string exceeds heap size limit

(System Code)
    at HttpApi.getError (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\jsforce\lib\http-api.js:250:13)
    at C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\jsforce\lib\http-api.js:95:22
    at tryCallOne (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\promise\lib\core.js:37:12)
    at C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\promise\lib\core.js:123:15
    at flush (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\asap\raw.js:50:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errorCode: 'APEX_ERROR'
}
The error is NOT BLOCKING O_O
how can we know if it's ok ?

LWC created and deployed but definitely not safe given the error

**Comment by AllanOricil** [comment] 2022-11-29 16:53
@PradeepSF how can I download the latest compiler?  Im currently using this prop in my job file

lwcCompilerVersion: 900.458.0

How can I specify I want the latest stable one.

**Comment by thvd** [comment] 2022-11-30 08:03
@AllanOricil usually within NPM you can specify `latest` so it does download the latest version. Can you try that?

**Comment by KevinGossentCap** [comment] 2022-11-30 08:11
@AllanOricil @thvd , since VBT 1.16, it's using latest to get latest version of omiscript & flexcard compilers.
So here we have vlocity/Salesforce provided components that have been "fixed" from "sessionStorage" issue but not tested to the point of knowing if there are further errors down the road while using localCompile on their own provided components.

I really say vlocity/Salesforce provided components because I'm directly testing with "industry CPQ LWC" components. I'd have to test with ESM components but I will not before it's solved for industry CPQ ones and I expect the solution provider to test it to the end.

**Closed** 2023-12-11 05:11 UTC
Labels: lwc compiler
