### ISSUE TITLE
CRITICAL ISSUE: Unable to finish deployment because the deployment is failing

### ISSUE THREAD

**Issue by Stepan007** [vlocityinc/vlocity_build#29] opened 2018-01-20 14:12 UTC
[exec] (node:88228) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ERROR_HTTP_414: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>
     [exec] (node:88228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[log.txt](https://github.com/vlocityinc/vlocity_build/files/1648869/log.txt)

**Comment by IIvanov8888** [comment] 2018-01-20 16:04
I saw this error few times before. Are you on the latest version of master ? 
You could try the following Deploy.yaml 
```yaml
projectPath: .
expansionPath: datapack-expanded
buildFile: MyDataPack.json
maxDepth: -1
maximumDeployCount: 1000
defaultMaxParallel: 1
exportPacksMaxSize: null
processMultiple: false
preStepApex:
    Deploy: DeactivateTemplatesAndLayouts.cls
delete: true
activate: true
```

**Comment by Codeneos** [comment] 2018-01-20 17:21
This is usually caused by the anonymous apex that gets execute prior to a deployment surpassing the maximum allowed number of lines that can be send as part of the URI. Anonymous APEX gets send as URL parameter instead of in the request body, this is a SalesForce thing,

If you ported your job file from an older version you need to remove the `preApex` configuration entries for `Deploy`.  If not please look at your `maximumDeployCount` entry, make sure it is not to high. Normally I go for a number around 10.

@IIvanov8888 ; the `maximumDeployCount` you are using is relatively high. Lower it to a more reasonable number such as 10 or 20. This will prevent the deployment tool from having to send large chunks of anonymous apex code to SalesForce.

**Comment by Stepan007** [comment] 2018-01-21 22:13
Hi both, thank you for your quick response! I have upgraded vlocity_build to the latest version. Then I have replaced preJobApex by preStepApex and it worked! Thank you very much

**Comment by rutlabaga** [comment] 2018-01-25 17:58
I am closing for now. I create a task to improve the error handling when the apex limit is too high.

**Closed by rutlabaga** 2018-01-25 17:58 UTC
