### ISSUE TITLE
How to handle Vlocity deployment failure with Git 

### ISSUE THREAD

**Issue by irfanlai** [vlocityinc/vlocity_build#541] opened 2022-12-05 17:26 UTC
I am using GitCheck true to deploy delta changes. 
I am trying to deploying multiple datapacks in a pull request. Assume I have 10 datapacks and the Vlocity deployment fails due to some file name issue or something which the dev has to fix on the Vlocity datapacks. 
Eight datapacks were success and two failed with errors.
Now when it fails the process does not creates a new Git Hash and neither it updates the VBT key in the org. When I see in the org the 8 datapacks were deployed. 
Now if I fix the remaining 2 datapacks and redeploy the same PR then it would deploy the 10 datapacks again which creates new ver for the 8 datapacks which were deployed earlier.
So how can I make sure that if it fails it should roll back all changes or the git hash should get updated? So next time when I try redeploying, it deploys only the delta.

**Scenario**: Use GitCheck True. Deploy 8-10 datapacks and make 1-2 fail due to some space in name issue or something similar. 
**Expected Result**: Either or the condition should be meet.
1. Complete deployment should rollback or
2. Githash should be updated with what was deployed successfully

**Actual Result**: Partial deployment is done and no GitHash is updated.

**Comment by tcvalente** [comment] 2022-12-12 13:51
Hi, from my experience, if the VBT fails the key is not updated since the deploy was marked as a failure. What we do in these scenarios is we manually update de vbt key in the org before relaunching the deploy. But we always have a new PR for the corrections/changes to the one that failed.

If you use a pipeline(for ex in jenkins) you can configure your pipeline to always update the VBT key if there is less than x errors.

But, in principle, i agree with you that if it fails, then it should rollback as in salesforce core. The problem is, vlocity deploys take so long (especialy if you have omni with LWC) that it would be a nightmare having it rolledback

**Closed** 2023-01-28 03:24 UTC

**Comment by irfanlai** [comment] 2023-02-07 16:33
> Hi, from my experience, if the VBT fails the key is not updated since the deploy was marked as a failure. What we do in these scenarios is we manually update de vbt key in the org before relaunching the deploy. But we always have a new PR for the corrections/changes to the one that failed.
> 
> If you use a pipeline(for ex in jenkins) you can configure your pipeline to always update the VBT key if there is less than x errors.
> 
> But, in principle, i agree with you that if it fails, then it should rollback as in salesforce core. The problem is, vlocity deploys take so long (especialy if you have omni with LWC) that it would be a nightmare having it rolledback

@tcvalente how can we update the VBT key if we are using GitHub Actions?

**Comment by tcvalente** [comment] 2023-02-08 09:46
With GitHub Actions it does present a challenge. In our case we use a Jenkins pipeline where we can set some inteligence to go and update the key if "errors < X".

With GitHub Actions i am not sure how to do this. Sorry...
