### ISSUE TITLE
Error Processing: Invalid conversion from runtime type List<ANY> to Map<String,ANY>

### ISSUE THREAD

**Issue by manuelepalmeri** [vlocityinc/vlocity_build#37] opened 2018-02-08 16:55 UTC
Hi,

Whit this job:
```
projectPath: output   
queries:
- VlocityDataPackType: OmniScript
  query: Select Id, %vlocity_namespace%__Type__c,  %vlocity_namespace%__SubType__c, %vlocity_namespace%__Language__c from %vlocity_namespace%__OmniScript__c where %vlocity_namespace%__IsActive__c = true
```

I get the following error:
```
  Exporting >> OmniScript Tecnico Verifica Apparati Di Rete Italian (a1v0E0000005wuHQAQ)
  Exporting >> OmniScript Tecnico Navigazione Lenta Italian (a1v0E0000005wQFQAY)
  DataPack API Error >> {
    "Message": "Error Processing: Invalid conversion from runtime type List<ANY> to Map<String,ANY>",
    "Status": "Error"
}
```

Any guess?

Thank you :)

**Comment by rutlabaga** [comment] 2018-02-08 17:07
What version of the Vlocity Package are you on? Was there anything after this?

You can try running:

vlocity packUpdateSettings

Which may eliminate the problem.

LIkely the issue is related to having some invalid duplicate data, like multiple Vlocity UI Templates or Vlocity Cards that are the same Name + Version number and are Active, but that is not very easy to figure out.

**Comment by manuelepalmeri** [comment] 2018-02-08 17:18
Hi,
thank you for the answer. 

I'm currently using Vlocity CMT 11.43.1. I get the same error even if I try to export with manifest and/or Dataraptors.

Unfortunately, I get some other errors with "packUpdateSettings" command:

```
Running Pre Job Apex >> ResetDataPackMappings.cls
  Loading Apex >> C:\Users\m.palmeri\vlocity_build-master\apex\ResetDataPackMappings.cls
  APEX Compilation Error >> Method is not visible: void vlocity_cmt.CorePostInstallClass.runDev2ProdInserts()
  Uncaught Job Error >> Method is not visible: void vlocity_cmt.CorePostInstallClass.runDev2ProdInserts()
```

**Comment by rutlabaga** [comment] 2018-02-08 17:44
Unfortunately, these tools will not work consistently until the Build Number switches to 900.X. Your only option is likely to continue to use the UI to Import / Export.

**Comment by manuelepalmeri** [comment] 2018-02-12 11:48
Hi rutlabaga,
so there is no way to use your script with my current Vlocity Package version?
My problem is that that I have some Omniscript too large to be exported with UI (i get "Apex CPU time limit exceeded" and "Apex heap size too large")

Thank you.

**Comment by manuelepalmeri** [comment] 2018-02-13 09:00
Hi rutlabaga,
can you explain better what you mean by "until the Build Number switches to 900.X"?

What I have to do in order to make the script work?

Best regards.

**Comment by manuelepalmeri** [comment] 2018-02-13 14:05
The problem seems to be in _runDataPackProcess()_ function during the Apex POST call (**datapacks.js line 188**). 

The request parameters generated by the scripts are the following:

```
{"body":"{
\"processType\":\"Export\",
\"processData\":{
   \"VlocityDataPackType\":\"OmniScript\",
   \"VlocityDataPackData\":
  [
    {
      \"Id\":\"a1v9E000002gV0xQAE\",
      \"%vlocity_namespace%__Language__c\":\"Italian\",
      \"%vlocity_namespace%__SubType__c\":\"Navigazione Lenta\",
      \"%vlocity_namespace%__Type__c\":\"Tecnico\",
      \"VlocityDataPackType\":\"OmniScript\",
      \"VlocityRecordSObjectType\":\"%vlocity_namespace%__OmniScript__c\",
      \"VlocityDataPackDisplayLabel\":\"Tecnico Navigazione Lenta Italian (a1v9E000002gV0xQAE)\"
    }
  ],
\"ignoreAllErrors\":false,
\"maxDepth\":-1,
\"alreadyExportedKeys\":[],
\"exportPacksMaxSize\":10}}",
"headers":{"Content-Type":"application/json"},
"method":"POST",
"url":"https://*****.my.salesforce.com/services/apexrest/vlocity_cmt/v1/VlocityDataPacks/"}
```
and the post request returns the following message (in "_result_"):
`{"Message":"Error Processing: Invalid conversion from runtime type List<ANY> to Map<String,ANY>","Status":"Error"}`

do you see any irregularity? 

Thank you

**Comment by rutlabaga** [comment] 2019-07-16 20:09
Managed Package issue. Should be fixed in recent versions.

**Closed by rutlabaga** 2019-07-16 20:09 UTC
