### ISSUE TITLE
Error when running "vlocity -propertyfile build_target.properties -job demo.yaml packDeploy" in target org

### ISSUE THREAD

**Issue by raghavendra1405** [vlocityinc/vlocity_build#149] opened 2019-01-18 10:35 UTC
SASS Compilation Error VlocityUITemplate/cpq-product-cart-item Failed to compile SCSS: vlocity_build\VlocityUITemplate\cpq-product-cart-item\cpq-product-cart-item.scss SASS compilation failed, see error message for details: Error:
        on line 2 of /stdin
>> @import "cpq-theme-variables";
   --------^

SASS Compilation Error VlocityUITemplate/cpq-product-cart Failed to compile SCSS: vlocity_build\VlocityUITemplate\cpq-product-cart\cpq-product-cart.scss SASS compilation failed, see error message for details: Error: Invalid CSS after "...oduct-cart.scss": expected "{", was ""
        on line 1 of /stdin
>> cpq-product-cart.scss

**Comment by thvd** [comment] 2019-01-31 10:48
I think this is a duplicate of #16. Please check if that issue helps you resolving it.

**Closed** 2022-11-09 18:45 UTC
